a = int(input("Enter first value: "))
b = int(input("Enter second value: "))
print("Addition of two numbers is:",a+b)
print("Subtraction of two numbers is:",a-b)
print("Multiplication of two numbers is:",a*b)
print("Division of two numbers is:",a/b)